/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author jpgea
 */
public class TelaPrototipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPrototipo
     */
    public TelaPrototipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        turma = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        principal = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        alunos = new javax.swing.JLabel();
        relatorio = new javax.swing.JLabel();
        ocorrencia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        professor = new javax.swing.JLabel();
        escola = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ajuda de sistema");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        turma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        turma.setForeground(new java.awt.Color(0, 0, 255));
        turma.setText("Cadastro de Turmas");
        turma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        turma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turmaMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/education_computer_school_graduate_cap_monitor_icon_149680.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ajuda do Sistema");

        principal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        principal.setForeground(new java.awt.Color(0, 0, 255));
        principal.setText("Tela Principal");
        principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalMouseClicked(evt);
            }
        });

        usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 255));
        usuario.setText("Cadastro de usuários");
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });

        alunos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alunos.setForeground(new java.awt.Color(0, 0, 255));
        alunos.setText("Cadastro de alunos");
        alunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alunosMouseClicked(evt);
            }
        });

        relatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        relatorio.setForeground(new java.awt.Color(0, 0, 255));
        relatorio.setText("Relatórios");
        relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatorioMouseClicked(evt);
            }
        });

        ocorrencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ocorrencia.setForeground(new java.awt.Color(0, 0, 255));
        ocorrencia.setText("Ocorrências");
        ocorrencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocorrenciaMouseClicked(evt);
            }
        });

        jLabel10.setText("Clique em algum dos tóricos abaixo para consultar a ajuda sobre cada");

        jLabel11.setText("tela disponível no sistema:");

        jLabel12.setText("Sejam bem-vindo ao Sistema de Informações Educacionais SIED.");

        jLabel13.setText("Sistema concebido com o objetivo de auxiliar o gerenciamento acadêmico ");

        jLabel14.setText("de uma unidade escolar.");

        professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        professor.setForeground(new java.awt.Color(0, 0, 255));
        professor.setText("Cadastro de Professores");
        professor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                professorMouseClicked(evt);
            }
        });

        escola.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        escola.setForeground(new java.awt.Color(0, 0, 255));
        escola.setText("Cadastro de Escolas");
        escola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(turma)
                            .addComponent(principal)
                            .addComponent(usuario)
                            .addComponent(alunos))
                        .addContainerGap(385, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(professor)
                                    .addComponent(escola))
                                .addGap(221, 221, 221))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatorio)
                            .addComponent(ocorrencia)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(principal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunos)
                .addGap(7, 7, 7)
                .addComponent(professor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocorrencia)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 420));

        setBounds(0, 0, 566, 391);
    }// </editor-fold>//GEN-END:initComponents

    private void turmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turmaMouseClicked
     TelaAjudaTurmas telaajudaturmas = new TelaAjudaTurmas();
        telaajudaturmas.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_turmaMouseClicked

    private void principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalMouseClicked
      TelaAjudaPrincipal telaajudaprincipal = new TelaAjudaPrincipal();
        telaajudaprincipal.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_principalMouseClicked

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
      TelaAjudaUsuarios telaajudausuarios = new TelaAjudaUsuarios();
        telaajudausuarios.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_usuarioMouseClicked

    private void alunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunosMouseClicked
        TelaAjudaAlunos telaajudaalunos = new TelaAjudaAlunos();
        telaajudaalunos.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_alunosMouseClicked

    private void relatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioMouseClicked
         TelaAjudaRelatorio telaajudarelatorio = new TelaAjudaRelatorio();
        telaajudarelatorio.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_relatorioMouseClicked

    private void ocorrenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocorrenciaMouseClicked
     TelaAjudaOcorrencia telaajudaocorrencia = new  TelaAjudaOcorrencia();
      telaajudaocorrencia.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_ocorrenciaMouseClicked

    private void professorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professorMouseClicked
         TelaAjudaProfessor telaajudaprofessor = new  TelaAjudaProfessor ();
      telaajudaprofessor.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_professorMouseClicked

    private void escolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escolaMouseClicked
       TelaAjudaEscolas telaajudaescolas = new  TelaAjudaEscolas  ();
      telaajudaescolas.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_escolaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alunos;
    private javax.swing.JLabel escola;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ocorrencia;
    private javax.swing.JLabel principal;
    private javax.swing.JLabel professor;
    private javax.swing.JLabel relatorio;
    private javax.swing.JLabel turma;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
